### ISSUE TITLE
Build error for Duplicate Jsr305_annotations.gwt.xml file

### ISSUE THREAD

**Issue by neha2016** [jwplayer/jwplayer-sdk-android-demo#12]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK jsr305_annotations/Jsr305_annotations.gwt.xml
>     File1: /home/user/jWPlayer-Sample/jwplayer-sdk-android-demo/app/build/intermediates/exploded-aar/com.longtailvideo.jwplayer/jwplayer-android-sdk/2.4.1+158/jars/classes.jar
>     File2: /home/user/jWPlayer-Sample/jwplayer-sdk-android-demo/app/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/9.0.0/jars/classes.jar

If I include 
packagingOptions
            {
                exclude 'jsr305_annotations/Jsr305_annotations.gwt.xml'
            }
in build.gradle file, then this error is solved but a runtime error is encountered which says
com.jwplayer.opensourcedemo E/AndroidRuntime: FATAL EXCEPTION: main
               Process: com.jwplayer.opensourcedemo, PID: 18212
                                                                             java.lang.NoSuchMethodError: No static method initialize(Landroid/content/Context;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/String;)Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager; in class Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager; or its super classes (declaration of 'com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager' appears in /data/data/com.jwplayer.opensourcedemo/files/instant-run/dex/slice-slice_8-classes.dex)
                                                                                 at com.longtailvideo.jwplayer.cast.CastManager.initialize(SourceFile:1099)
                                                                                 at com.jwplayer.opensourcedemo.MyApplication.onCreate(MyApplication.java:15)
                                                                                 at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369)
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4554)
                                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by RikHeijdens** [comment]
Could you confirm that your CastCompanionLibrary-android directory is not empty?

**Comment by neha2016** [comment]
Yes, it's non-empty

**Comment by RikHeijdens** [comment]
Couple of questions:

Did you make any changes to the project, besides including the JW Player libraries and adding your key to the AndroidManifest.xml file?

Are you using instant run? If so, does this issue occur when you disable instant run?

If you go into the CastCompanionLibrary-android directory, what is the output of `git status`?

**Comment by neha2016** [comment]
No, I did not make any changes other than adding JW Player libraries and key.

I am using instant run. When I disabled the same, the following errors occured:
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzr;
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

git status produces the following output:
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   build.gradle

no changes added to commit (use "git add" and/or "git commit -a")

Which, I think, is just because I removed compilation dependency once, but added it back. And the file 'build.gradle' is same as before, now.

**Comment by Retto** [comment]
I have the some problem. Is there a progress ?

**Comment by RikHeijdens** [comment]
I haven't been able to reproduce this - could you please upload your project somewhere (without license key) so that I can take a look at it?

One thing that does seem a bit odd is the inclusion of Google Play Services 9, that may be clashing with version 8, which is included by the CastCompanionLibrary.

**Comment by northwoodcutter** [comment]
I also have this problem. Has anyone found a solution?

**Comment by GMSyrimis** [comment]
Please refer to our documentation if you're still having issues and contact JW Player support from the JW Player Dashboard.
https://developer.jwplayer.com/sdk/android/docs/developer-guide/

**Comment by badrscrpion** [comment]
good luck on the way I can do that. www
