### ISSUE TITLE
Widevine drm content not playing on Android 7.1.2 

### ISSUE THREAD

**Issue by raa-ju** [jwplayer/jwplayer-sdk-android-demo#127]
Hello,
I am facing a drm related problem while playing video, I used jwplayer 4.10.2 version. It throws error code 276005. the log says

```
2023-10-16 15:45:58.973 4136-9782/? E/WVCdm: Decrypt error result in session sid38 during encrypted block: 176
2023-10-16 15:45:58.973 4136-9782/? E/WVCdm: WVCryptoPlugin::decrypt else E
2023-10-16 15:45:58.976 10187-10351/? E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.4D401E, 2309363, null, [720, 480, 29.97], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:43)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Unknown Error
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2480)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SourceFile:3)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(SourceFile:75)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:18)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:15)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:25)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

please give me suggestions that may help. Thanks

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket).
