### ISSUE TITLE
Picture In Picture registration crashes on Android sdk level 34[Android 14] due to : SecurityException RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED  

### ISSUE THREAD

**Issue by freny-John** [jwplayer/jwplayer-sdk-android-demo#129]
E  FATAL EXCEPTION: main
    Process: com.n21mobile, PID: 2577
    java.lang.SecurityException: com.n21mobile: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
    	at android.os.Parcel.createException(Parcel.java:3041)
    	at android.os.Parcel.readException(Parcel.java:3024)
    	at android.os.Parcel.readException(Parcel.java:2966)
    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5703)
    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
    	at com.longtailvideo.jwplayer.m.b.a(SourceFile:227)
    	at com.jwplayer.a.c.a(SourceFile:1108)
    	at com.jwplayer.a.c.$r8$lambda$lP2nEPCyYi6Q8O_pk9DldgnjccI(Unknown Source:0)
    	at com.jwplayer.a.c$$ExternalSyntheticLambda1.run(Unknown Source:6)
    	at android.os.Handler.handleCallback(Handler.java:958)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:232)
    	at android.os.Looper.loop(Looper.java:334)
    	at android.app.ActivityThread.main(ActivityThread.java:8291)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
    Caused by: android.os.RemoteException: Remote stack trace:
    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14249)
    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2579)
    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2798)
    	at android.os.Binder.execTransactInternal(Binder.java:1339)
    	at android.os.Binder.execTransact(Binder.java:1275)
---------------------------- PROCESS ENDED (2577) for package com.n21mobile ----------------------------
---------------------------- PROCESS STARTED (3218) for package com.n21mobile ----------------------------

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

This seems to be a valid issue, so please escalate this through our standard channels.
