### ISSUE TITLE
java.lang.IllegalStateException at android.media.MediaCodec.dequeueOutputBuffer(Native Method)

### ISSUE THREAD

**Issue by hforhajar** [jwplayer/jwplayer-sdk-android-demo#15]
I have an exception error when playing some video (with JW Player), but the other video is playing well. 

this is the error message: 
`Internal runtime error.
	Java.lang.IllegalStateException
     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
     at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(SourceFile:889)
     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(SourceFile:512)
     at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SourceFile:129)
     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(SourceFile:434)
     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:213)
     at android.os.Handler.dispatchMessage(Handler.java:98)
     at android.os.Looper.loop(Looper.java:136)
     at android.os.HandlerThread.run(HandlerThread.java:61)
     at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)`

I don't know why, but there's no MediaCodec on my project file. Before i use JW Player as my player on my project, i use another player and that video is playing well. Is there something wrong? or maybe I forgot to add 'something' to my source code?

**Comment by RikHeijdens** [comment]
Hi @hforhajar,

We use MediaCodec internally for video playback.
Could you please share the stream or video that you are having issues with, so I can look into this?

Thanks,
Rik

**Comment by hforhajar** [comment]
Hi @RikHeijdens,

Thanks for replaying,
this is the url video : http://www.metube.id/videos/433691/TzDSsjeFQnnFG0q6y31f/
you can also check http://cdn.metube.co.id/videom3u8/6yax6yM8Gdt73JS3MYZZ/index.m3u8

Thank you

**Comment by RikHeijdens** [comment]
That stream plays for me on a Nexus 5X with Android 7.0, is there a particular device you are having issues on?

**Comment by hforhajar** [comment]
sorry, my mistake.. there's an error on my team code when try to encode the video, 
and it is solved. thank you @RikHeijdens for helping :)

**Comment by Vaishnavi-optisol** [comment]
@RikHeijdens 
I'm having the same kind of issue when playing m3u8 format url but this happens only in some devices.

Device Details
Name : Moto e 2nd generation
Android Version : 5.1
