### ISSUE TITLE
Sdk not working for me

### ISSUE THREAD

**Issue by AbhiHearty** [jwplayer/jwplayer-sdk-android-demo#17]
When i clone or download and opened i am facing a crash denoting no class found in cast library

**Comment by AbhiHearty** [comment]
java.lang.NoClassDefFoundError: com.google.android.libraries.cast.companionlibrary.cast.CastConfiguration$Builder
                                                                                 at com.longtailvideo.jwplayer.cast.CastManager.a(SourceFile:117)
                                                                                 at com.longtailvideo.jwplayer.cast.CastManager.initialize(SourceFile:89)
                                                                                 at com.jwplayer.opensourcedemo.MyApplication.onCreate(MyApplication.java:15)
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4749)
                                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:172)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:146)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5653)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

1.

**Comment by paulmandal** [comment]
Hey AbhiHearty, it looks like you don't have the CastCompanion library included in your project.  Instructions for adding it are here: https://developer.jwplayer.com/sdk/android/docs/developer-guide/chromecast/getting-started/

Please let me know if you have any questions!

**Comment by AbhiHearty** [comment]
Hi paulmandal, I have the library in sdk format and i have now replaced with the gradle dependency and i hope i dint see the initialisation problem. I am having few queries the encryption of videos .

**Comment by GMSyrimis** [comment]
Chromecast issue is resolved, closing issue.
