### ISSUE TITLE
JWPlayerView inside Custom Fragment Crash

### ISSUE THREAD

**Issue by offline-first** [jwplayer/jwplayer-sdk-android-demo#37]
FATAL EXCEPTION: main
                                     Process: ch.fcb.fcbasel1893, PID: 30627
                                     java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                         at com.longtailvideo.jwplayer.b.j$1.onOrientationChanged(SourceFile:30)
                                         at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
                                         at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:699)
                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                         at android.os.MessageQueue.next(MessageQueue.java:323)
                                         at android.os.Looper.loop(Looper.java:136)
                                         at android.app.ActivityThread.main(ActivityThread.java:6123)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

Is there any working solution inside a Fragment Layout?

**Comment by WilsonGarcia4190** [comment]
I am having the same issue, did you find a workaround?

**Comment by mr-techiee** [comment]
Hi team,
am also facing this same issue.. would u plz close this one ASAP?

**Comment by mwaked** [comment]
Hello, I have also the same issue .. Any update??

**Comment by GMSyrimis** [comment]
Hey everyone, in general, the best way to get support for SDK issues is by submitting a support ticket with our team. In the meantime, we have a new Demo showcasing Custom Fragments here:
https://github.com/jwplayer/jwplayer-android-best-practice-apps/pull/572

From the looks of it, you should use the `Activity` when setting up the player and you should also look into creating your own `FullscreenHandler` if it's still an issue.
