### ISSUE TITLE
HttpDataSource$HttpdataSourceException 

### ISSUE THREAD

**Issue by Allan-Nava** [jwplayer/jwplayer-sdk-android-demo#44]
I have this problem:
```

E/ExoPlayerImplInternal: Internal track renderer error.
                                                                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://portal.seafy.me/Web/FILES/public/vod/3_days_to_kill_trailer_it.mp4
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SourceFile:263)
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SourceFile:149)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(SourceFile:275)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:205)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
                                                                          Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://portal.seafy.me/Web/FILES/public/vod/3_days_to_kill_trailer_it.mp4
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(SourceFile:195)
                                                                             at com.longtailvideo.jwplayer.c.a.open(SourceFile:153)
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:824)
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
                                                                             at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
                                                                             at com.android.okhttp.Connection.connect(Connection.java:143)
                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                             at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(SourceFile:421)
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(SourceFile:343)
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(SourceFile:193)
                                                                             at com.longtailvideo.jwplayer.c.a.open(SourceFile:153) 
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:824) 
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209) 
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
                                                                             at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
                                                                             at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                             at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103) 
                                                                             at com.android.okhttp.Connection.connect(Connection.java:143) 
                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437) 
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
                                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
                                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(SourceFile:421) 
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(SourceFile:343) 
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(SourceFile:193) 
                                                                             at com.longtailvideo.jwplayer.c.a.open(SourceFile:153) 
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:824) 
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209) 
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
                                                                          Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324) 
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225) 
                                                                             at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556) 
                                                                             at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324) 
                                                                             at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103) 
                                                                             at com.android.okhttp.Connection.connect(Connection.java:143) 
                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437) 
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
                                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
                                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(SourceFile:421) 
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(SourceFile:343) 
                                                                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(SourceFile:193) 
                                                                             at com.longtailvideo.jwplayer.c.a.open(SourceFile:153) 
                                                                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:824) 
                                                                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209) 
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
```

**Comment by RikHeijdens** [comment]
Looks like an issue with the certificate for `portal.seafy.me`.

**Comment by Allan-Nava** [comment]
@RikHeijdens I solve with trust all certificate, but is not the best solution. Thanks by the way

**Comment by aitbaali** [comment]
@Allan-Nava How did manage to trust all certificate, and in which level did you handle that?
