### ISSUE TITLE
Issue in my App and in So many Times

### ISSUE THREAD

**Issue by Digvesh** [jwplayer/jwplayer-sdk-android-demo#48]
Exception: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:831)
at com.longtailvideo.jwplayer.core.c.d.a(SourceFile:215)
at com.longtailvideo.jwplayer.core.d.c.onPageFinished(SourceFile:101)
at com.android.webview.chromium.Ap.onPageFinished(WebViewContentsClientAdapter.java:196)
at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:70)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by okulagin** [comment]
Hi @Digvesh ,

Does it happen when you are trying to create/destroy the player multiple times in a row?

**Comment by Digvesh** [comment]
Actually Yes we have create new Player when pull to refresh in application. but not in row.

**Comment by okulagin** [comment]
@Digvesh please try to use the most recent version of the SDK which is 2.7.11. The issue should be fixed there
