### ISSUE TITLE
in Library Crash how to prevent?

### ISSUE THREAD

**Issue by Digvesh** [jwplayer/jwplayer-sdk-android-demo#49]
Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-4
at java.util.ArrayList.get(ArrayList.java:413)
at java.util.Collections$UnmodifiableList.get(Collections.java:1295)
at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(SourceFile:495)
at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(SourceFile:710)
at com.google.android.exoplayer.hls.HlsSampleSource.onLoadCompleted(SourceFile:432)
at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(SourceFile:245)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)

**Comment by okulagin** [comment]
Hello @Digvesh ,

Could you provide me with the stream that you are using please?

**Comment by Digvesh** [comment]
Actually i am not provide stream due proprietary. but i suggest it's .m3u8 format file.

**Comment by okulagin** [comment]
@Digvesh please try to use the most recent version of the SDK which is 2.7.11. The issue might be fixed there
