### ISSUE TITLE
 Response code: 302

### ISSUE THREAD

**Issue by Digvesh** [jwplayer/jwplayer-sdk-android-demo#52]
internalError [1.39, loadError]
                                                                                     com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
                                                                                         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
                                                                                         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
                                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
                                                                                         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                         at java.lang.Thread.run(Thread.java:818)

**Can you please help us for solve this. it's not work when url is redirected. Please help**

**Comment by GMSyrimis** [comment]
@Digvesh Please build with the latest SDK and if you are still having issues provide the following:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
