### ISSUE TITLE
CastManager initialize error

### ISSUE THREAD

**Issue by ki6358** [jwplayer/jwplayer-sdk-android-demo#6]
04-07 11:09:19.109 24630-24630/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.jwplayer.opensourcedemo, PID: 24630
                                                   java.lang.NoSuchMethodError: No static method initialize(Landroid/content/Context;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/String;)Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager; in class Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager; or its super classes (declaration of 'com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager' appears in /data/app/com.jwplayer.opensourcedemo-1/base.apk)
                                                       at com.longtailvideo.jwplayer.cast.CastManager.initialize(SourceFile:1100)
                                                       at com.jwplayer.opensourcedemo.MyApplication.onCreate(MyApplication.java:15)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5252)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:182)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6141)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

How can i resolve it?

**Comment by RikHeijdens** [comment]
Could you verify that the CastCompanionLibrary-android folder is not empty?

**Comment by GMSyrimis** [comment]
Issue should now be resolved. It seemed to be a missing menu item. Closing issue.

**Comment by neha2016** [comment]
Hi! I am having the same error and cannot solve this issue. Please help.

**Comment by neha2016** [comment]
I am having the exact same problem and unable to use jw player on android. Please help.

**Comment by vincekennedy** [comment]
@neha2016 This issue is because version [2.7.0](https://github.com/googlecast/CastCompanionLibrary-android/commit/f63f5c4e4ea7117be2ebf69ac43ad80e2be07447#diff-e950a3ba98081d9736f60ca26d6d8e1e) of CastCompanionLibrary removed the `initialize(Context, String, Class, String)` method in favor of `.initalize(Context, CastConfiguration)`.

Add an older version of the library and you should be able to build and run the project.
