### ISSUE TITLE
Crash in JW Player 3.0.0+53

### ISSUE THREAD

**Issue by FrancescoSantagati** [jwplayer/jwplayer-sdk-android-demo#61]
> java.lang.AbstractMethodError: abstract method "void com.longtailvideo.jwplayer.events.listeners.VideoPlayerEvents$OnPlaylistListener.onPlaylist(com.longtailvideo.jwplayer.events.PlaylistEvent)"
        at com.longtailvideo.jwplayer.core.a.e$23.run(SourceFile:409)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by hyunjkim** [comment]
@FrancescoSantagati, there were a few modifications and additions, you can find the list of eventlisteners here: [https://developer.jwplayer.com/sdk/android/reference/com/longtailvideo/jwplayer/events/listeners/package-summary.html](https://developer.jwplayer.com/sdk/android/reference/com/longtailvideo/jwplayer/events/listeners/package-summary.html)
