### ISSUE TITLE
Java exception raised in Player

### ISSUE THREAD

**Issue by macroday** [jwplayer/jwplayer-sdk-android-demo#66]
Hi,

Somtimes, I am getting java exception in Jwplayer android. Please tell me the solution.

Here the exception stack,

`I/chromium: [INFO:CONSOLE(1)] "Uncaught Error: Java exception was raised during method invocation", source: http://intercept.jw//data/user/0/com.play.mobo/files/jwplayer/jw_core/html5_provider_mobile.js (1)
W/System.err: java.lang.VerifyError: com.longtailvideo.jwplayer.g.b.c$7
        at com.longtailvideo.jwplayer.g.b.c.a(Unknown Source)
        at com.longtailvideo.jwplayer.g.b.e.play(Unknown Source)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by GMSyrimis** [comment]
@macroday This has been submitted a while ago. I'm going to close this thread. If you find an issue please provide the following:

*Issue Summary:* 

*JWP SDK Ver #:* 

*OS Version:* 

*Device make & model:* 

*IDE:* 

*Video or Screenshots:* 

*Demo App source code experiencing the issue:* 

*Steps to reproduce:* 
# 

*Expected Behavior:* 

*Actual Behavior:* 

*Log / Stack Trace of exceptions, errors, etc:*
