### ISSUE TITLE
onError listener has not been called on Android SDK

### ISSUE THREAD

**Issue by OmarJoya** [jwplayer/jwplayer-sdk-android-demo#67]
Hi,

I'm trying to validate when an url is not found, but onErrorListener neither onSetupErrorListener methods are been called , also throws an exception into onError base method

jwplayer version 
3.1.0+58

`08-16 21:00:37.947 1748-1788/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
08-16 21:00:38.352 32426-32426/com.sciodev.zenither.qa E/EventLogger: internalError [0.81, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
08-16 21:00:38.860 32426-32426/com.sciodev.zenither.qa E/EventLogger: internalError [1.32, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
08-16 21:00:40.362 32426-32426/com.sciodev.zenither.qa E/EventLogger: internalError [2.83, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
08-16 21:00:42.841 32426-300/com.sciodev.zenither.qa E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
08-16 21:00:42.897 32426-32426/com.sciodev.zenither.qa E/EventLogger: internalError [5.36, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
08-16 21:00:42.900 32426-32426/com.sciodev.zenither.qa E/EventLogger: playerFailed [5.36]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:355)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(SourceFile:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(SourceFile:141)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:737)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
08-16 21:00:45.456 32426-32593/com.sciodev.zenither.qa W/System.err: org.json.JSONException: No value for message
08-16 21:00:45.457 32426-32593/com.sciodev.zenither.qa W/System.err:     at org.json.JSONObject.get(JSONObject.java:392)
        at org.json.JSONObject.getString(JSONObject.java:553)
        at com.longtailvideo.jwplayer.core.a.e.onError(SourceFile:507)
08-16 21:00:45.458 32426-32593/com.sciodev.zenither.qa W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
`

![image](https://user-images.githubusercontent.com/11036913/44234859-440cd900-a16d-11e8-81d5-36a4f6e2278a.png)

and the videoplayer does not display any error message, only this

![image](https://user-images.githubusercontent.com/11036913/44235047-dd3bef80-a16d-11e8-91a5-3c3ae0776af6.png)

Thank you

**Comment by nizamofhyd** [comment]
I see the same issue on jwplayer version
3.1.0+58, VideoPlayerEvents.OnErrorListener is not invoked .

Steps to replicate:
Play any content and put the app in flight mode

**Comment by GMSyrimis** [comment]
Using version 3.7.1 of the SDK, the onError callback will provide this error message in this scenario:
"This video cannot be played because of a problem with your internet connection."

Closing the stale thread
