### ISSUE TITLE
Chromecast Exception

### ISSUE THREAD

**Issue by LSanfordCarbonTV** [jwplayer/jwplayer-sdk-android-demo#84]
Chromecast works in the demo using the JWPlayerViewExample but when I switch to the JWPlayerFragmentExample, Chromecast does not work.

I get this exception:

W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1258)
        at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:946)
        at com.longtailvideo.jwplayer.player.b.a(SourceFile:71)
        at com.longtailvideo.jwplayer.core.b.c.b(SourceFile:613)
        at com.longtailvideo.jwplayer.core.b.c.lambda$KKq-c0CL8OUUV8V3aqUouMdJew4(Unknown Source:0)
        at com.longtailvideo.jwplayer.core.b.-$$Lambda$c$KKq-c0CL8OUUV8V3aqUouMdJew4.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)

**Comment by AlexandruStroiaDev** [comment]
Same here :(

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. Closing this thread as it's fairly old
