### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by paveu-piotrowski** [jwplayer/jwplayer-sdk-android-demo#86]
I made a slight modification to the demo app: 
Created a new activity (A) that hosts a fragment. PlayerView is a view in fragment's view hierarchy. The thing is, when I navigate back from activity A, I get a leak. 
PlayerView is just a part of view hierarchy, it wasn't even initialized with config.

`2019-07-03 11:36:33.987 12892-12892/com.jwplayer.opensourcedemo E/ActivityThread: Activity com.jwplayer.opensourcedemo.JWPlayerFragmentExample has leaked IntentReceiver com.google.android.exoplayer2.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver@25a99eb that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.jwplayer.opensourcedemo.JWPlayerFragmentExample has leaked IntentReceiver com.google.android.exoplayer2.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver@25a99eb that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1469)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1236)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1479)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1452)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1440)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
        at com.google.android.exoplayer2.audio.AudioCapabilitiesReceiver.register(AudioCapabilitiesReceiver.java:93)
        at com.longtailvideo.jwplayer.player.c.b(SourceFile:593)
        at com.longtailvideo.jwplayer.player.c.<init>(SourceFile:213)
        at com.longtailvideo.jwplayer.core.p.a(SourceFile:211)
        at com.longtailvideo.jwplayer.JWPlayerView.a(SourceFile:245)
        at com.longtailvideo.jwplayer.JWPlayerView.<init>(SourceFile:168)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.jwplayer.opensourcedemo.FragmenntJW.onCreateView(FragmentJW.java:17)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1470)
        at android.app.Activity.performStart(Activity.java:7170)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3061)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)`

Also a screenshot from LeakCanary (other app, but the same activity-fragment-view relation):
![signal-attachment-2019-07-03-120503](https://user-images.githubusercontent.com/9088821/60583436-306d5f80-9d8b-11e9-80ef-d603c32fe686.jpeg)

**Comment by hyunjkim** [comment]
Hi, @paveu-piotrowski , can you provide your demo app?

**Comment by hyunjkim** [comment]
@paveu-piotrowski , did you also add JWPlayer's lifecycle (just in case)?

- https://developer.jwplayer.com/sdk/android/docs/developer-guide/getting-started/add-a-player-to-an-activity/

	@Override
	protected void onStart() {
		super.onStart();
		mPlayerView.onStart();
	}

	@Override
	protected void onResume() {
		// Let JW Player know that the app has returned from the background
		super.onResume();
		mPlayerView.onResume();
	}

	@Override
	protected void onPause() {
		// Let JW Player know that the app is going to the background
		mPlayerView.onPause();
		super.onPause();
	}
	@Override
	protected void onStop() {
		super.onStop();
		mPlayerView.onStop();
	}

	@Override
	protected void onDestroy() {
		// Let JW Player know that the app is being destroyed
		mPlayerView.onDestroy();
		super.onDestroy();
	}

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. Closing this thread as it's fairly old.

**Comment by katjarutnik** [comment]
@paveu-piotrowski were you able to resolve this issue and how?
