### ISSUE TITLE
Crashing the app

### ISSUE THREAD

**Issue by rahoboth** [jwplayer/jwplayer-sdk-android-demo#9]
FATAL EXCEPTION: main
                                                                           Process: com.jwplayer.opensourcedemo, PID: 1874
                                                                           java.lang.AssertionError: License Edition INVALID is not valid for JW Player Android SDK.
                                                                               at com.longtailvideo.jwplayer.license.segmentation.b$1.run(SourceFile:82)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5233)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by RikHeijdens** [comment]
Please make sure that you've replaced `{YOUR_LICENSE_KEY}` with your license key in the [AndroidManifest.xml](https://github.com/jwplayer/jwplayer-sdk-android-demo/blob/master/app/src/main/AndroidManifest.xml#L27) file.

**Comment by rahoboth** [comment]
I still not bought your jwplayer kit, but the process for buying your Android SDK is in progress. Before that I need to test your demo code, with our server url. I had integrated this demo and while running the code. Error is coming..

**Comment by RikHeijdens** [comment]
Please [contact](https://www.jwplayer.com/contact-us/) our sales team and request a free trial key. Once you received your trial key you should be able to use this demo app.

**Comment by rahoboth** [comment]
Thank you, I requested to your sales team. 
Waiting for your reply asap.

**Comment by iqualtech** [comment]
best solution for this is dont test player with emulator for android

**Comment by RikHeijdens** [comment]
@iqualtech This error is not specific to the emulator.
